# Generated by Django 3.2.15 on 2022-09-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('profile', models.ManyToManyField(blank=True, null=True, to='main.Profile')),
            ],
        ),
    ]
