# Generated by Django 3.2.15 on 2022-09-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='profile',
            field=models.ManyToManyField(blank=True, to='main.Profile'),
        ),
    ]
